### ISSUE TITLE
[WINDOWS] Notify me when WIRK is minimized and I'm mentioned in a channel

### ISSUE THREAD

**Issue by banderso-n** [technicallyerik/WIRK#34] opened 2013-06-18 16:25 UTC
When someone mentions me in a message and WIRK is minimized, it'd be nice if it flashed in the taskbar or something to let me know I have a message directed at me.

**Comment by technicallyerik** [comment] 2013-06-18 16:27
Duplicate of #19

**Closed as completed by technicallyerik** 2013-06-18 16:27 UTC
Labels: duplicate, enhancement
